# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
# 注意更改文件夹

name: Push site to Other repository

on:
  # 在针对 `main` 分支的推送上运行。如果您
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [main]

  # 允许您从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      
      # 如果使用 pnpm，请取消注释
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm # 或 pnpm / yarn / npm
          # cache-dependency-path: subdir/pnpm-lock.yaml # subdir/package-lock.json

      - name: Install dependencies
        run: pnpm install # 或 pnpm install / yarn install / bun install / npm ci
      - name: Build with VitePress
        run: |
          pnpm run build
          mv ./README.md ./dist/README.md

          # 推送到<username>.github.io main中的一个文件夹
          # 下面要发布的内容所在的文件夹写 ./publ 就能实现
          # mkdir ./publ
          # mv docs/.vitepress/dist ./publ/blog

      # [强制推送，会清除原来仓库里的所有文件]自动推送到<username>.github.io仓库里
      - name: publish
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:jlower/jlower.github.io.git # 目标库的ssh链接
          BRANCH: main # 目标分支
          FOLDER: ./dist # 要发布的内容所在的文件夹

          # 将之前在Github账号内录入过公钥的SSH生成的密钥添加到当前仓库的 Secrets 中
          # 在 GitHub 仓库页面的 Settings > Secrets and variables > Actions > Repository secrets 中，点击 “New repository secret”，
          # 然后将密钥名称设置为 SSH_PRIVATE_KEY，密钥值设置为之前在Github账号内录入过公钥的SSH生成的密钥。
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

